default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["CUSTOMER_DASHBOARD_DATABASE_USERNAME"] %>
  password: <%= ENV["CUSTOMER_DASHBOARD_DATABASE_PASSWORD"] %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["CUSTOMER_DASHBOARD_DATABASE_NAME"] %>

test:
  <<: *default
  database: customer_dashboard_test

production:
  <<: *default
  password: <%= ENV["CUSTOMER_DASHBOARD_DATABASE_PASSWORD"] %>
