# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin "@rails/ujs", to: "@rails--ujs.js"
pin "bootstrap", to: "vendor/bootstrap/dist/js/bootstrap.min.js"
pin "popper", to: "vendor/@popperjs/core/dist/umd/popper.min.js"
# pin "onscreen", to: "vendor/onscreen/dist/on-screen.umd.min.js"
pin "nouislider", to: "vendor/nouislider/distribute/nouislider.min.js"
pin "smooth-scroll", to: "vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"
pin "chartist", to: "vendor/chartist/dist/chartist.min.js"
# pin "chartist-plugin-tooltip", to: "vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"
pin "datepicker", to: "vendor/vanillajs-datepicker/dist/js/datepicker.min.js"
pin "sweetalert2", to: "vendor/sweetalert2/dist/sweetalert2.all.min.js"
pin "notyf", to: "vendor/notyf/notyf.min.js"
pin "simplebar", to: "vendor/simplebar/dist/simplebar.min.js"
# pin "volt", to: "volt.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin_all_from "app/javascript/lib", under: "lib"
